"""Book page_count

Revision ID: c5dfc16bdc66
Revises: a585fd97b88c
Create Date: 2026-01-23 00:09:14.192263

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c5dfc16bdc66"
down_revision: Union[str, None] = "a585fd97b88c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("page_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "page_count")
    # ### end Alembic commands ###
